# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo
    pod 'GoogleMaps', '5.1.0'
    pod 'Google-Maps-iOS-Utils', '3.10.3'
    pod 'Alamofire', '~> 4.7'
    #pod 'AlamofireObjectMapper', '~> 5.0'
    #pod 'AlamofireNetworkActivityLogger', '~> 2.3'
end
